language: cpp

matrix:
  include:
    #GCC with C++17 Support
    - os: linux
      env: BUILD_SHARED=OFF
    - os: osx
      osx_image: xcode8
      env: BUILD_SHARED=OFF

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake; brew install sdl2; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-8 xorg-dev libglu1-mesa-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi

before_script:
  - if [ -z "$BUILD_SHARED" ]; then export BUILD_SHARED=ON; fi
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED=$BUILD_SHARED ..

script:
  - make