language: cpp

matrix:
  include:
    - name: "GCC 8 - Static"
      os: linux
      env: BUILD_SHARED=OFF
    - name: "GCC 8 - Shared"
      os: linux
      env: BUILD_SHARED=ON

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-8 xorg-dev libglu1-mesa-dev doxygen ncftp; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi

before_script:
  - if [ -z "$BUILD_SHARED" ]; then export BUILD_SHARED=ON; fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NGINE_SHARED=$BUILD_SHARED -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..

script:
  - make
  
after_success:
  - ncftpput -avR -u ${SFTP_USER} -p ${SFTP_PASSWORD} ftp://ftp.nerdthings.dev /docs/test docs/docs/html
