language: cpp

matrix:
  include:
    #GCC with C++17 Support
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_SHARED=OFF

	- os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_SHARED=ON

    #- os: osx
    #  osx_image: xcode8
    #  env:
    #    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    #CLANG with C++11 Support
    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #        - llvm-toolchain-precise-3.6
    #      packages:
    #        - clang-3.6
    #  env:
    #    - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - if [ -z "BUILD_SHARED" ]; then export BUILD_SHARED=ON ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake; brew install sdl2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev libglu1-mesa-dev; fi
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED=$BUILD_SHARED ..

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" || "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi